Repository rh-ecosystem-edge/ztp-pipeline-relocatable, pull requests merged in 2022-06, with the labels that each got.

#307 MGMT-10345 [ZTPFW] Change Error messages by warn
  deploy-disconnected-registry/ocp-sync.sh
  deploy-disconnected-registry/olm-sync.sh
  pipelines/bootstrap.sh
  shared-utils/verify_preflight.sh
Labels: internal, pipelines, registry, test-ci

#349 UI: Update test snapshots
  ui/frontend/src/components/ApiAddressPage/__snapshots__/ApiAddressPage.test.tsx.snap
  ui/frontend/src/components/IngressIpPage/__snapshots__/IngressIpPage.test.tsx.snap
Labels: ui

#350 MGMT-10594 Ease rules for IPv4 validation
  ui/frontend/src/components/utils.ts
Labels: ui

#325 MGMT-10183 Move "Optional" badge on the Domain Page
  ui/frontend/src/components/DomainPage/DomainSelector.tsx
  ui/frontend/src/components/DomainPage/__snapshots__/DomainPage.test.tsx.snap
  ui/frontend/src/components/DomainPage/__snapshots__/DomainSelector.test.tsx.snap
Labels: ui, test-ci-ui

#345 ci(labeler): disable labeler as it's lacking currently permissions
  .github/workflows/testing-pr.yml
  pipelines/bootstrap.sh
  shared-utils/verify_preflight.sh
Labels: internal, pipelines, github-actions

#323 MGMT-10555 Limit password's character set
  ui/backend/src/common/validation.ts
  ui/frontend/src/components/PasswordPage/PasswordRequirements.tsx
  ui/frontend/src/components/PasswordPage/__snapshots__/PasswordPage.test.tsx.snap
  ui/frontend/src/components/PasswordPage/utils.ts
Labels: ui, test-ci-ui

#346 ci(size): Add size label for the code change
  .github/workflows/size.yaml
Labels: skip-ci, internal, github-actions

#337 fix: mgmt-10251-change default size vm and odf storagecluster manifest to 1
  deploy-odf/manifests/04-ODF-StorageCluster.yaml
  hack/deploy-hub-local/create-vm.yml
Labels: internal, test-ci, odf, ok-to-merge, size/XS

#367 ci(broken-link): use v2.3.0
  .github/workflows/broken-link-check.yml
Labels: skip-ci, size/XS

#371 ci(broken-link): ignore docs.github.com
  .github/workflows/broken-link-check.yml
Labels: skip-ci, size/XS

#372 ci(broken-link): gihub actions array format
  .github/workflows/broken-link-check.yml
Labels: skip-ci, internal, github-actions, size/XS

#374 ci(broken-link): use with instead of env
  .github/workflows/broken-link-check.yml
Labels: skip-ci, internal, github-actions, size/XS

#379 internal(clean-scripts): add script to clean libvirt pool
  hack/clean/clean-edges.sh
  hack/clean/clean-libvirt-pool.sh
Labels: skip-ci, size/M

#380 internal(clean-scripts): take in account more use cases and options
  hack/clean/clean-libvirt-pool.sh
Labels: enhancement, skip-ci, internal

#386 ansible(packages): add fpaste as common pkg
  hack/deploy-hub-local/ansible/tasks/base/01-packages.yaml
Labels: skip-ci, internal, ansible, size/XS

#388 clean(libvirt-pool): control unbound
  hack/clean/clean-libvirt-pool.sh
Labels: skip-ci, size/L

#384 fix(registry): Add certificate to OpenShift objects to be able to pull after ICSP
  deploy-disconnected-registry/common.sh
  shared-utils/common.sh
Labels: internal, pipelines, registry, test-ci, images, size/M, edgecluster

#287 Adding option to run bootstrap with local copy
  pipelines/bootstrap.sh
Labels: pipelines, test-ci, size/M

#348 Feat: MGMT-10649 add one interface instead of 2
  Makefile
  deploy-edgecluster/render_edgeclusters.sh
  deploy-worker/render_worker.sh
  documentation/ztp-for-factories/ztp-for-factory-edgeclusters-yaml.adoc
  documentation/ztp-for-factories/ztp-for-factory-pipeline-edge.adoc
  documentation/ztp-for-factories/ztp-for-factory-prerequisites.adoc
  documentation/ztp-for-factories/ztp-install-factory-edge-pipeline.adoc
  documentation/ztp-for-factories/ztp-install-factory-hubedge-architecture.adoc
  examples/config.yaml
  hack/deploy-hub-local/build-edgecluster.sh
  hack/deploy-hub-local/create-vm-sno.yml
  hack/deploy-hub-local/create-vm.yml
Labels: documentation, skip-ci, internal, worker, edge, size/L, edgecluster

#381 MGMT-10782: recreate PullSecret on each run
  .gitignore
  Makefile
  shared-utils/common.sh
Labels: internal, test-ci, size/S

#278 Don't pass the starting CSV version
  contrib/gpu-operator/deploy.sh
  contrib/gpu-operator/manifests/03-gpu-subscription.yaml
Labels: test-ci, contrib, size/XS

#398 Fix lab-dns-internal to pass shellcheck linter
  hack/deploy-hub-local/lab-dns-internal.sh
Labels: internal, size/XS

#399 Fix lab-dns-external to pass shellcheck linter
  hack/deploy-hub-local/lab-dns-external.sh
Labels: internal, size/XS

#397 Fix shared-utils to pass shellcheck linter
  shared-utils/common.sh
Labels: internal, test-ci, size/XS

#401 Fix deploy-edgecluster to pass shellcheck linter
  deploy-edgecluster/configure_disconnected.sh
Labels: test-ci, size/XS, edgecluster

#402 fix(hub-config/deploy): Remove obsolete Hive patch
  deploy-hub-configs/deploy.sh
Labels: test-ci, size/XS

#405 MGMT-10407: Disable the Save button when no change
  ui/frontend/src/components/K8SStateContext.tsx
  ui/frontend/src/components/PersistPage/PersistPageBottom.tsx
  ui/frontend/src/components/Settings/Settings.tsx
  ui/frontend/src/components/Settings/SettingsPageRight.tsx
  ui/frontend/src/components/WelcomePage/WelcomePage.tsx
  ui/frontend/src/components/WelcomePage/initialDataLoad.ts
  ui/frontend/src/components/types.ts
Labels: ui, size/L

#396 Need to export BRANCH earlier
  pipelines/bootstrap.sh
Labels: pipelines, test-ci, size/XS

#410 fix(Makefile): reverse clean order
  Makefile
Labels: skip-ci, size/XS

#412 ci(housekeeping): clean old container resources
  .github/workflows/build-and-push-release.yml
Labels: skip-ci, size/XS

#416 ci(ui): fix first if
  .github/workflows/ui.yml
Labels: skip-ci, size/XS

#422 Log git-hash in the Browser's console log
  ui/frontend/package.json
  ui/frontend/src/index.tsx
  ui/frontend/src/sha.ts
Labels: size/S

#423 Ci Bootstrap before pipeline
  .github/workflows/testing-pr.yml
Labels: internal, test-ci, github-actions, size/XS

#426 Move getting UI git sha to Dockerfile
  images/Containerfile.UI
  ui/frontend/package.json
Labels: size/XS

#430 UI: Update react-scripts 5.0.1 and eslint to 8.18.0
  ui/backend/package.json
  ui/backend/yarn.lock
  ui/frontend/package.json
  ui/frontend/yarn.lock
Labels: size/L

#429 re-enabling UI testing
  .github/workflows/testing-pr.yml
Labels: Hold, internal, test-ci-ui, github-actions, size/XS

#409 Unify eviction code into common function
  deploy-disconnected-registry/deploy.sh
  deploy-edgecluster/configure_disconnected.sh
  shared-utils/common.sh
Labels: internal, registry, test-ci, size/L, edgecluster, ready-to-merge

#433 MGMT-10846: Fix setting "clean" snapshot for isDirty comparision
  ui/frontend/src/components/K8SStateContext.tsx
Labels: size/M

#431 [UI] Be more talkative for the user waiting for data to be persisted
  ui/frontend/src/components/PersistPage/PersistPageBottom.tsx
  ui/frontend/src/components/PersistPage/__snapshots__/PersistPage.test.tsx.snap
Labels: ui, size/M

#434 MGMT-10892 Safe navigation to the /wizard/persist page for no change
  ui/frontend/src/components/K8SStateContext.tsx
  ui/frontend/src/components/PersistPage/PersistPageBottom.tsx
  ui/frontend/src/components/PersistPage/persist.ts
Labels: ui, size/S

#437 [UI] Fix unit tests
  ui/frontend/package.json
  ui/frontend/src/components/PersistPage/__snapshots__/PersistPage.test.tsx.snap
  ui/frontend/src/setupTests.ts
  ui/frontend/yarn.lock
Labels: ui, test-ci-ui, size/M

#443 updating Clusters_0422_network_image to show optional int network
  documentation/ztp-for-factories/images/225_OpenShift_Installing_Clusters_0422_network.png
Labels: documentation, size/XS

#444 ci(labels): label al UI pr's to perform test-ci-ui automatically
  .github/labels.yml
Labels: github-actions, size/XS

#353 fix(edgeclusters.sh): Workaround BZ 2073197 issue with signatures on containers
  images/Containerfile.pipeline
Labels: pipelines, test-ci, edge, images, size/XS, edgecluster, ready-to-merge

#442 MGMT-10892 Request confirmation before leaving the persist page
  ui/frontend/src/components/PersistPage/persist.ts
  ui/frontend/src/components/Settings/SettingsPageRight.tsx
  ui/frontend/src/components/utils.ts
Labels: ui, test-ci-ui, size/M

#445 revert: Revert signatures workaround
  deploy-edgecluster/render_edgeclusters.sh
  images/Containerfile.pipeline
Labels: pipelines, images, size/XS, edgecluster

#446 Revert "fix(Makefile): reverse clean order"
  Makefile
Labels: size/XS

#440 MGMT-10897 Make the persistence synchronous
  ui/frontend/src/components/PersistPage/persist.ts
  ui/frontend/src/components/PersistPage/persistDomain.ts
  ui/frontend/src/components/PersistPage/persistIdentityProvider.ts
  ui/frontend/src/components/PersistPage/persistServices.ts
  ui/frontend/src/components/PersistPage/utils.ts
  ui/frontend/src/components/PersistProgress/PersistProgress.tsx
Labels: ui, test-ci-ui, size/L

#448 [UI] Update yarn and run tests synchronously
  images/Containerfile.UI
  ui/package.json
Labels: ui, test-ci-ui, images, size/S

#450 [UI] Unregister OnUnloadPage handler sooner
  ui/frontend/src/components/PersistPage/persist.ts
Labels: ui, test-ci-ui, size/XS

#453 ci(.precommit): Add shellcheck
  .pre-commit-config.yaml
Labels: size/L
