Repository rh-ecosystem-edge/ztp-pipeline-relocatable, pull requests merged in 2022-03, with the labels that each got.

#73 UI unit tests
  ui/frontend/.eslintrc
  ui/frontend/package.json
  ui/frontend/src/App.test.tsx
  ui/frontend/src/App.tsx
  ui/frontend/src/components/ApiAddressPage/ApiAddressPage.test.tsx
  ui/frontend/src/components/ApiAddressPage/ApiAddressSelector.test.tsx
  ui/frontend/src/components/ApiAddressPage/ApiAddressSelector.tsx
  ui/frontend/src/components/ApiAddressPage/__snapshots__/ApiAddressPage.test.tsx.snap
  ui/frontend/src/components/ApiAddressPage/__snapshots__/ApiAddressSelector.test.tsx.snap
  ui/frontend/src/components/IngressIpPage/IngressIpPage.test.tsx
  ui/frontend/src/components/IngressIpPage/IngressIpSelector.test.tsx
  ui/frontend/src/components/IngressIpPage/IngressIpSelector.tsx
  ui/frontend/src/components/IngressIpPage/__snapshots__/IngressIpPage.test.tsx.snap
  ui/frontend/src/components/IngressIpPage/__snapshots__/IngressIpSelector.test.tsx.snap
  ui/frontend/src/components/IpTriplet/IpTriplet.tsx
  ui/frontend/src/components/IpTripletsSelector/IpTripletsSelector.tsx
  ui/frontend/src/components/K8SStateContext.tsx
  ui/frontend/src/components/PersistPage/persistServices.ts
  ui/frontend/src/components/Redirect.tsx
  ui/frontend/src/components/Wizard/Wizard.tsx
  ui/frontend/src/components/utils.test.ts
  ui/frontend/src/components/utils.ts
  ui/frontend/src/resources/oauth.ts
  ui/frontend/src/resources/resource-request.ts
  ui/frontend/src/resources/utils.test.ts
  ui/frontend/src/setupTests.ts
  ui/frontend/yarn.lock
  ui/package.json
Labels: Hold

#105 Add Documentation to the project
  .github/workflows/codeql-analysis.yml
  .gitignore
  Makefile
  documentation/ztp-for-factories/images/pipeline-hub-workflow.png
  documentation/ztp-for-factories/images/pipeline-spoke-workflow.png
  documentation/ztp-for-factories/images/tkn-pr-describe-tasks.png
  documentation/ztp-for-factories/images/tkn-pr-ls.png
  documentation/ztp-for-factories/images/tkn-tr-describe.png
  documentation/ztp-for-factories/main.adoc
  documentation/ztp-for-factories/ztp-for-factory-development.adoc
  documentation/ztp-for-factories/ztp-for-factory-installation-workflow.adoc
  documentation/ztp-for-factories/ztp-for-factory-labtesting.adoc
  documentation/ztp-for-factories/ztp-for-factory-overview.adoc
  documentation/ztp-for-factories/ztp-for-factory-pipeline-edge.adoc
  documentation/ztp-for-factories/ztp-for-factory-pipeline-hub.adoc
  documentation/ztp-for-factories/ztp-for-factory-prerequisites.adoc
  documentation/ztp-for-factories/ztp-for-factory-troubleshooting.adoc
  website/1.0/ZTP-for-factories.html
  website/1.0/ZTP-for-factories.pdf
  website/_data/devprev.yml
  website/_data/releases.yml
  website/_data/static.yml
  website/_data/versioned.yml
  website/index.html
Labels: under-review

#119 Run CI only when 'skip-ci' is not present
  .github/workflows/testing-pr.yml
Labels: enhancement, skip-ci

#111 Some enhancement to the storage section
  documentation/ztp-for-factories/ztp-for-factory-prerequisites.adoc
Labels: documentation, skip-ci

#114 Doc enhancement to the troubleshooting section
  documentation/ztp-for-factories/ztp-for-factory-troubleshooting.adoc
Labels: documentation, skip-ci

#112 Some enhancement to the flow section
  documentation/ztp-for-factories/ztp-for-factory-installation-workflow.adoc
Labels: documentation, skip-ci

#113 Pipeline hub doc enhancements
  documentation/ztp-for-factories/ztp-for-factory-pipeline-hub.adoc
Labels: documentation, skip-ci

#117 Add autolabelling GHA
  .github/labels.yml
  .github/workflows/label.yml
Labels: skip-ci

#125 UI: Fix random failing of "yarn install" in CI
  .github/workflows/ui.yml
  ui/package.json
Labels: GHA, ui

#124 UI: Patch existing AddressPool instead of creating a new one
  ui/frontend/src/components/PersistPage/constants.ts
  ui/frontend/src/components/PersistPage/persist.ts
  ui/frontend/src/components/PersistPage/persistServices.ts
  ui/frontend/src/components/PersistPage/resourceTemplates.ts
Labels: skip-ci, ui

#134 Ignore Network interfaces
  documentation/ztp-for-factories/ztp-for-factory-prerequisites.adoc
  documentation/ztp-for-factories/ztp-for-factory-spokes-yaml.adoc
  examples/config.yaml
Labels: documentation, skip-ci

#140 fix(common-git-fetch.yaml): remove ndots option in resolv.conf to avo…
  pipelines/resources/common/common-git-fetch.yaml
Labels: bug, pipelines

#139 MGMT-9698 Revoke kubeadmin password
  ui/frontend/src/components/PersistPage/constants.ts
  ui/frontend/src/components/PersistPage/persist.ts
  ui/frontend/src/components/PersistPage/persistIdentityProvider.ts
  ui/frontend/src/components/UsernamePage/UsernameSelector.tsx
  ui/frontend/src/components/UsernamePage/__snapshots__/UsernamePage.test.tsx.snap
  ui/frontend/src/components/UsernamePage/__snapshots__/UsernameSelector.test.tsx.snap
  ui/frontend/src/resources/secret.ts
Labels: ui

#106 Add image build steps in makefiles (with branch)
  .github/workflows/testing-pr.yml
  Makefile
  images/Containerfile.pipeline
  pipelines/resources/common/common-pre-flight-spokes.yaml
  pipelines/resources/common/common-pre-flight.yaml
  pipelines/resources/deploy-ztp-hub.yaml
  pipelines/resources/deploy-ztp-spokes.yaml
  pipelines/resources/hub/hub-deploy-acm.yaml
  pipelines/resources/hub/hub-deploy-disconnected-registry.yaml
  pipelines/resources/hub/hub-deploy-httpd-server.yaml
  pipelines/resources/hub/hub-deploy-hub-config.yaml
  pipelines/resources/hub/hub-deploy-icsp.yaml
  pipelines/resources/hub/hub-save-config.yaml
  pipelines/resources/spokes/kustomization.yaml
  pipelines/resources/spokes/spoke-deploy-disconnected-registry-spokes.yaml
  pipelines/resources/spokes/spoke-deploy-icsp-spokes-post.yaml
  pipelines/resources/spokes/spoke-deploy-icsp-spokes-pre.yaml
  pipelines/resources/spokes/spoke-deploy-metallb.yaml
  pipelines/resources/spokes/spoke-deploy-ocs.yaml
  pipelines/resources/spokes/spoke-deploy-spoke.yaml
  pipelines/resources/spokes/spoke-deploy-ui.yaml
  pipelines/resources/spokes/spoke-deploy-workers.yaml
  pipelines/resources/spokes/spoke-detach-cluster.yaml
  pipelines/resources/spokes/spoke-restore-hub-config.yaml
Labels: GHA, pipelines

#144 UI: Read api/ingress IP from status as a fallback
  ui/frontend/src/components/WelcomePage/initialDataLoad.ts
  ui/frontend/src/resources/service.ts
Labels: skip-ci, ui

#145 Update gitignore
  .gitignore
  ui/.gitignore
Labels: skip-ci

#149 Resources tekton - multithreading
  deploy-disconnected-registry/olm-sync.sh
  pipelines/resources/hub/hub-deploy-disconnected-registry.yaml
  pipelines/resources/spokes/spoke-deploy-disconnected-registry-spokes.yaml
Labels: pipelines, registry
