Repository rh-ecosystem-edge/ztp-pipeline-relocatable, pull requests merged in 2022-05, with the labels that each got.

#203 fix: Root is not necessary to execute the bootstrap script, removing
  pipelines/bootstrap.sh
Labels: skip-ci, pipelines

#206 Change way we get agent IP for metallb
  deploy-metallb/deploy.sh
Labels: metallb

#210 Add a clean target to add cleaning steps
  Makefile
Labels: skip-ci

#205 Patch routes selectively
  ui/backend/src/common/resources/deployment.ts
  ui/backend/src/common/resources/index.ts
  ui/backend/src/common/resources/oauthclient.ts
  ui/backend/src/common/resources/pod.ts
  ui/backend/src/common/resources/route.ts
  ui/backend/src/constants.ts
  ui/backend/src/endpoints/changeDomain.ts
  ui/backend/src/endpoints/liveness.ts
  ui/backend/src/endpoints/readiness.ts
  ui/backend/src/k8s/json-request.ts
  ui/backend/src/k8s/oauth.ts
  ui/backend/src/k8s/respond.ts
  ui/backend/src/resources/deployment.ts
  ui/backend/src/resources/oauthclient.ts
  ui/backend/src/resources/route.ts
  ui/frontend/src/components/ActionCountDown/index.tsx
  ui/frontend/src/components/PersistPage/PersistPageBottom.tsx
  ui/frontend/src/components/PersistPage/constants.ts
  ui/frontend/src/components/PersistPage/persist.ts
  ui/frontend/src/components/PersistPage/persistServices.ts
  ui/frontend/src/components/PersistPage/utils.ts
  ui/frontend/src/components/Settings/SettingsPageRight.tsx
  ui/frontend/src/index.tsx
  ui/frontend/src/resources/pod.ts
Labels: ui

#215 Refactored, modularized and documented ansible hypervisor playbooks
  hack/deploy-hub-local/ansible/.gitignore
  hack/deploy-hub-local/ansible/README.md
  hack/deploy-hub-local/ansible/ansible.cfg
  hack/deploy-hub-local/ansible/setup.yaml
  hack/deploy-hub-local/ansible/tasks/base/00-base.yaml
  hack/deploy-hub-local/ansible/tasks/base/01-services.yaml
  hack/deploy-hub-local/ansible/tasks/base/02-bin-utils.yaml
  hack/deploy-hub-local/ansible/tasks/base/chrony.yaml
  hack/deploy-hub-local/ansible/tasks/base/ssh.yaml
  hack/deploy-hub-local/ansible/tasks/services/chronyd/00-chrony-base.yaml
  hack/deploy-hub-local/ansible/tasks/services/libvirtd/00-libvirtd.yaml
  hack/deploy-hub-local/ansible/tasks/services/sshd/00-sshd-base.yaml
  hack/deploy-hub-local/ansible/tasks/services/sshd/01-sshd-configure.yaml
  hack/deploy-hub-local/ansible/tasks/services/sshd/02-sshd-fail2ban.yaml
Labels: skip-ci, internal

#200 MGMT-9937: Fix Logout
  ui/backend/src/endpoints/configure.ts
  ui/backend/src/endpoints/index.ts
  ui/backend/src/index.ts
  ui/backend/src/k8s/cookies.ts
  ui/backend/src/k8s/oauth.ts
  ui/frontend/src/App.tsx
  ui/frontend/src/components/ApiAddressPage/__snapshots__/ApiAddressPage.test.tsx.snap
  ui/frontend/src/components/DomainPage/__snapshots__/DomainPage.test.tsx.snap
  ui/frontend/src/components/DownloadSshKeyPage/__snapshots__/DownloadSshKeyPage.test.tsx.snap
  ui/frontend/src/components/FinalPage/__snapshots__/FinalPage.test.tsx.snap
  ui/frontend/src/components/IngressIpPage/__snapshots__/IngressIpPage.test.tsx.snap
  ui/frontend/src/components/Page/HeaderTools.tsx
  ui/frontend/src/components/PasswordPage/__snapshots__/PasswordPage.test.tsx.snap
  ui/frontend/src/components/PersistPage/__snapshots__/PersistPage.test.tsx.snap
  ui/frontend/src/components/Settings/__snapshots__/Settings.test.tsx.snap
  ui/frontend/src/components/UsernamePage/__snapshots__/UsernamePage.test.tsx.snap
  ui/frontend/src/components/WelcomePage/__snapshots__/WelcomePage.test.tsx.snap
Labels: ui

#209 SNO-DNS
  deploy-hub-configs/deploy.sh
Labels: spoke

#220 MGMT-10240 - Mask crio-wipe systemd unit
  deploy-spoke/render_spokes.sh
  finish-deployment/deploy.sh
Labels: Hold, spoke, finalization

#214 MGMT-9989 - Patching the Node Root CA by hand instead of using MCO
  deploy-disconnected-registry/deploy.sh
  deploy-httpd-server/deploy.sh
  deploy-hub-configs/deploy.sh
  deploy-ui/deploy.sh
  shared-utils/common.sh
  shared-utils/wait_for_deployment.sh
Labels: enhancement, ui, registry, test-ci, finalization

#223 Moving the ui and workers steps earlier in the pipeline
  pipelines/resources/deploy-ztp-spokes.yaml
Labels: pipelines

#218 Add custom SA to approve csr
  deploy-spoke/csr_autoapprover.sh
  finish-deployment/deploy.sh
Labels: spoke, test-ci, finalization

#231 Fix some files with errors detected with precommit
  contrib/README.md
  contrib/gpu-operator/deploy.sh
  contrib/gpu-operator/manifests/04-nfd-gpu-feature.yaml
  contrib/gpu-operator/verify.sh
  contrib/template/deploy.sh
  contrib/template/verify.sh
  deploy-disconnected-registry/common.sh
  deploy-disconnected-registry/deploy.sh
  deploy-disconnected-registry/ocp-sync.sh
  deploy-disconnected-registry/olm-sync.sh
  deploy-disconnected-registry/verify.sh
  deploy-spoke/configure_disconnected.sh
  deploy-spoke/csr_autoapprover.sh
  deploy-spoke/render_spokes.sh
  finish-deployment/deploy.sh
  hack/deploy-hub-local/lab-dns-external.sh
  hack/deploy-hub-local/lab-dns-internal.sh
  pipelines/resources/spokes/spoke-deploy-disconnected-registry-spokes-ps.yaml
  shared-utils/common.sh
  shared-utils/verify_preflight.sh
  shared-utils/wait_for_sno_mco.sh
Labels: internal, pipelines, spoke, registry, finalization

#240 Fixing small typos
  documentation/ztp-for-factories/ztp-for-factory-pipeline-edge.adoc
  documentation/ztp-for-factories/ztp-for-factory-pipeline-hub.adoc
Labels: documentation, skip-ci

#239 Adding under spokes.yaml file
  documentation/ztp-for-factories/ztp-for-factory-spokes-yaml.adoc
Labels: documentation

#249 Add set-motd utility
  hack/set-motd/README.md
  hack/set-motd/go.mod
  hack/set-motd/main.go
Labels: skip-ci, internal

#247 Fix add gpu operator
  contrib/gpu-operator/deploy.sh
  contrib/gpu-operator/manifests/03-gpu-subscription.yaml
  contrib/gpu-operator/verify.sh
  deploy-spoke/configure_disconnected.sh
  pipelines/resources/deploy-ztp-spokes.yaml
Labels: pipelines, spoke, test-ci

#250 Add tests to set-motd
  hack/set-motd/main.go
  hack/set-motd/main_test.go
Labels: enhancement, under-review, skip-ci, internal

#233 Change naming from OCS to ODF
  .github/labels.yml
  Makefile
  deploy-disconnected-registry/deploy.sh
  deploy-odf/deploy.sh
  deploy-odf/manifests/01-LSO-Namespace.yaml
  deploy-odf/manifests/01-ODF-Namespace.yaml
  deploy-odf/manifests/02-LSO-OperatorGroup.yaml
  deploy-odf/manifests/02-ODF-OperatorGroup.yaml
  deploy-odf/manifests/03-LSO-Subscription.yaml
  deploy-odf/manifests/03-ODF-Subscription.yaml
  deploy-odf/manifests/04-LSO-LocalVolume.yaml
  deploy-odf/manifests/04-ODF-StorageCluster.yaml
  deploy-odf/verify.sh
  documentation/ztp-for-factories/ztp-for-factory-installation-workflow.adoc
  documentation/ztp-for-factories/ztp-for-factory-pipeline-edge.adoc
  documentation/ztp-for-factories/ztp-for-factory-prerequisites.adoc
  documentation/ztp-for-factories/ztp-for-factory-spokes-yaml.adoc
  examples/config.yaml
  hack/deploy-hub-local/build-hub.sh
  hack/deploy-hub-local/build-spoke.sh
  hack/env
  pipelines/resources/deploy-ztp-spokes.yaml
  pipelines/resources/spokes/kustomization.yaml
  pipelines/resources/spokes/spoke-deploy-odf.yaml
  shared-utils/common.sh
Labels: documentation, GHA, internal, pipelines, registry

#248 MGMT-10009 Add monitoring of operators before UI redirect
  ui/backend/src/common/resources/clusteroperator.ts
  ui/backend/src/common/resources/index.ts
  ui/backend/src/common/resources/pod.ts
  ui/backend/src/common/resources/statuscondition.ts
  ui/backend/src/k8s/oauth.ts
  ui/frontend/src/App.tsx
  ui/frontend/src/components/PersistPage/PersistPageBottom.css
  ui/frontend/src/components/PersistPage/PersistPageBottom.tsx
  ui/frontend/src/components/PersistPage/__snapshots__/PersistPage.test.tsx.snap
  ui/frontend/src/components/PersistPage/constants.ts
  ui/frontend/src/components/PersistPage/persist.ts
  ui/frontend/src/components/PersistPage/persistDomain.ts
  ui/frontend/src/components/PersistPage/persistIdentityProvider.ts
  ui/frontend/src/components/PersistPage/persistServices.ts
  ui/frontend/src/components/PersistPage/utils.ts
  ui/frontend/src/components/PersistProgress/PersistProgress.tsx
  ui/frontend/src/components/PersistProgress/index.ts
  ui/frontend/src/components/Settings/SettingsPageRight.css
  ui/frontend/src/components/Settings/SettingsPageRight.tsx
  ui/frontend/src/components/Settings/__snapshots__/Settings.test.tsx.snap
  ui/frontend/src/components/utils.ts
  ui/frontend/src/resources/clusteroperator.ts
  ui/frontend/src/resources/resource-request.ts
Labels: Hold, ui

#252 Added new features
  hack/deploy-hub-local/ansible/README.md
  hack/deploy-hub-local/ansible/ansible.cfg
  hack/deploy-hub-local/ansible/setup.yaml
  hack/deploy-hub-local/ansible/tasks/base/00-base-network.yaml
  hack/deploy-hub-local/ansible/tasks/base/00-base-os.yaml
  hack/deploy-hub-local/ansible/tasks/base/01-base-network.yaml
  hack/deploy-hub-local/ansible/tasks/base/01-packages.yaml
  hack/deploy-hub-local/ansible/tasks/base/02-bin-utils.yaml
  hack/deploy-hub-local/ansible/tasks/files/bashrc
  hack/deploy-hub-local/ansible/tasks/finalizers/99-finalizers.yaml
  hack/deploy-hub-local/ansible/tasks/services/00-services-common.yaml
  hack/deploy-hub-local/ansible/tasks/services/chronyd/00-chrony-base.yaml
  hack/deploy-hub-local/ansible/tasks/services/libvirtd/00-libvirtd.yaml
  hack/deploy-hub-local/ansible/tasks/services/logrotate/00-logrotate-base.yaml
  hack/deploy-hub-local/ansible/tasks/services/sshd/00-sshd-base.yaml
  hack/deploy-hub-local/ansible/tasks/services/sshd/01-sshd-configure.yaml
  hack/deploy-hub-local/ansible/tasks/services/sshd/02-sshd-fail2ban.yaml
  hack/deploy-hub-local/ansible/tasks/services/tuned/00-tuned-base.yaml
Labels: skip-ci, internal

#253 Add ignore_errors
  hack/deploy-hub-local/ansible/tasks/services/chronyd/00-chrony-base.yaml
Labels: skip-ci, internal

#254 feat(ci): set motd when a worker is in use
  .github/workflows/set-motd.yml
Labels: skip-ci

#255 feat(ci): set/unset motd when a worker start or finishes being used by CI
  .github/workflows/testing-pr.yml
Labels: skip-ci

#261 fix(setmotd): removing max args in setmotd set
  hack/set-motd/main.go
Labels: skip-ci, internal

#262 fix(ansible): clean repo before cloning
  hack/deploy-hub-local/ansible/tasks/base/02-bin-utils.yaml
Labels: skip-ci

#263 fix(ci): fix set-motd variables
  .github/workflows/testing-pr.yml
Labels: skip-ci, GHA

#264 fix(ci): reduce set-motd verbose
  .github/workflows/testing-pr.yml
Labels: skip-ci, GHA

#266 feat(ansible): add set-motd help in bashrc
  hack/deploy-hub-local/ansible/tasks/files/bashrc
Labels: skip-ci

#267 fix(ansible): bashrc messages break ansible
  hack/deploy-hub-local/ansible/tasks/files/bashrc
Labels: skip-ci

#269 Adjust task name
  .github/workflows/testing-pr.yml
Labels: GHA

#259 Re-enable worker after it was accidentally disabled
  pipelines/resources/deploy-ztp-edgeclusters.yaml
Labels: pipelines, test-ci

#270 fix(ansible): small motd fix
  hack/deploy-hub-local/ansible/tasks/base/02-bin-utils.yaml
Labels: skip-ci

#272 fix(ansible): current duplicated word
  hack/deploy-hub-local/ansible/tasks/base/02-bin-utils.yaml
Labels: skip-ci

#275 Add tektonconfig definition
  pipelines/bootstrap.sh
  pipelines/manifests/02-tektonconfig.yaml
Labels: pipelines

#285 fix(ansible): control hub and edge function errors properly
  hack/deploy-hub-local/ansible/tasks/files/bashrc
Labels: skip-ci

#286 fix(registry): fix the registry route check
  deploy-disconnected-registry/deploy.sh
Labels: registry

#289 fix(registry): selinux patch to handle BZ#2033639
  deploy-disconnected-registry/deploy.sh
Labels: registry

#290 feat(ansible): add some minor tweak to bashrc
  hack/deploy-hub-local/ansible/tasks/files/bashrc
Labels: skip-ci, internal

#294 feat(ci): adapt ui ci to new workflow
  .github/workflows/ui.yml
Labels: skip-ci, test-ci-ui

#315 Combine several PR's that fix the pipeline deployment
  Makefile
  deploy-acm/deploy.sh
  deploy-disconnected-registry/deploy.sh
  deploy-disconnected-registry/manifests/machine-config-certs-master.yaml
  deploy-disconnected-registry/manifests/machine-config-certs-worker.yaml
  deploy-edgecluster/render_edgeclusters.sh
  deploy-edgecluster/verify.sh
  deploy-odf/deploy.sh
  deploy-odf/manifests/04-ODF-StorageCluster.yaml
  deploy-worker/render_worker.sh
  finish-deployment/deploy.sh
  hack/deploy-hub-local/ansible/tasks/base/01-packages.yaml
  hack/deploy-hub-local/ansible/tasks/services/sshd/00-mosh-base.yaml
  hack/deploy-hub-local/bootstrap-ci.sh
  pipelines/bootstrap.sh
  shared-utils/common.sh
Labels: internal, pipelines, worker, registry, acm, test-ci, finalization, odf, edgecluster

#298 build: Enable mosh
  hack/deploy-hub-local/ansible/tasks/base/01-packages.yaml
  hack/deploy-hub-local/ansible/tasks/services/sshd/00-mosh-base.yaml
Labels: enhancement, Hold, internal

#301 fix(render_edgeclusters.sh): Fix interface iteration for creating ign…
  deploy-edgecluster/render_edgeclusters.sh
Labels: bug, edgecluster

#309 fix(ODF): Set back replicas to 3 because of lack of stability
  deploy-odf/manifests/04-ODF-StorageCluster.yaml
Labels: bug, odf

#321 ci(needsrebase): Add CI for testing if PR needs rebase
  .github/workflows/needs-rebase.yaml
Labels: skip-ci

#313 MGMT-10593 Prevent using the same IP address for both Ingress and API
  ui/frontend/src/components/ApiAddressPage/ApiAddressPage.tsx
  ui/frontend/src/components/IngressIpPage/IngressIpPage.tsx
  ui/frontend/src/components/K8SStateContext.tsx
  ui/frontend/src/components/WelcomePage/initialDataLoad.ts
  ui/frontend/src/components/utils.ts
Labels: ui

#314 MGMT-10549 Inform about success after kubeadmin removal
  ui/frontend/src/components/PersistPage/constants.ts
  ui/frontend/src/components/Settings/DeleteKubeadminButton.tsx
Labels: ui

#328 ci(labels.yaml): add labels to test-ui-ci when touching code there
  .github/labels.yml
Labels: GHA

#330 ci(testing-pr): Autoadd/remove label 'ok-to-merge' based on test status
  .github/workflows/testing-pr.yml
Labels: GHA

#324 MGMT-10554 Rephrase the UsernamePage
  ui/frontend/src/components/UsernamePage/UsernameSelector.tsx
  ui/frontend/src/components/UsernamePage/__snapshots__/UsernamePage.test.tsx.snap
  ui/frontend/src/components/UsernamePage/__snapshots__/UsernameSelector.test.tsx.snap
Labels: ui, test-ci-ui

#334 ci(ansible): fine-tunning the ansible workflow
  .github/labels.yml
  .github/workflows/ci-test-ansible.yml
  .gitleaks.toml
  hack/deploy-hub-local/ansible/inventory-ci
  hack/deploy-hub-local/ansible/tasks/base/00-base-os.yaml
Labels: test-ci-ansible, ansible

#335 ci(ui.yaml): run UI ci only when there are commits for it
  .github/workflows/ui.yml
Labels: GHA

#327 ci(ui.yaml): attempt to add yarn to cache to speed up builds
  .github/workflows/ui.yml
Labels: enhancement, GHA, ui, test-ci-ui

#333 ci(testing-pr.yaml): skip UI generation errors to not block other tests
  .github/workflows/testing-pr.yml
Labels: GHA, test-ci

#329 fix(Containerfile): add netcat for SNO DNS testing and workaround
  images/Containerfile.pipeline
Labels: test-ci
