Repository rh-ecosystem-edge/ztp-pipeline-relocatable, pull requests merged in 2023-01, with the labels that each got.

#638 Use matching ginkgo version in GitHub actions
  .github/workflows/check-cli.yml
  ztp/go.mod
  ztp/go.sum
Labels: internal, github-actions, size/S

#639 Enhancing the doc.
  documentation/ztp-for-factories/ztp-install-openshift-pipelines.adoc
Labels: documentation, size/XS

#637 MGMT-12539: Migrate to 4.11
  Makefile
  deploy-disconnected-registry/oc-mirror-config-edgecluster.yaml
  deploy-disconnected-registry/oc-mirror-config-hub.yaml
  deploy-disconnected-registry/verify_olm_sync.sh
  deploy-edgecluster/render_edgeclusters.sh
  deploy-hub-configs/deploy.sh
  deploy-hub-configs/registryconf.txt
  deploy-lvmo/manifests/05-Hub-PVC.yaml
  deploy-mce/03-subscription.yml
  deploy-metallb/deploy.sh
  deploy-metallb/manifests/02-MLB-OperatorGroup.yaml
  deploy-metallb/manifests/address_pool.yaml
  deploy-metallb/verify.sh
  deploy-worker/change_def_route.sh
  deploy-worker/render_worker.sh
  pipelines/resources/edgeclusters/edgecluster-deploy-disconnected-registry-edgeclusters-ps.yaml
  pipelines/resources/edgeclusters/edgecluster-deploy-disconnected-registry-edgeclusters.yaml
  pipelines/resources/edgeclusters/edgecluster-deploy-icsp-edgeclusters-post.yaml
  pipelines/resources/hub/hub-deploy-hub-config.yaml
  pipelines/resources/hub/hub-deploy-update-global-ps.yaml
Labels: pipelines, metallb, worker, registry, size/L, edgecluster

#643 Disable UI build failures
  .github/workflows/jekyll.yml
  .github/workflows/ui.yml
Labels: documentation, size/XS

#647 NO-ISSUE: Increase golangci-lint timeout
  .github/workflows/check-cli.yml
Labels: size/XS

#641 NO-ISSUE: Add CLI logging infrastructure
  ztp/go.mod
  ztp/go.sum
  ztp/internal/cmd/edgecluster/edgecluster_cmd_test.go
  ztp/internal/cmd/version/version_cmd_test.go
  ztp/internal/context.go
  ztp/internal/context_test.go
  ztp/internal/logger.go
  ztp/internal/logger_test.go
  ztp/internal/suite_test.go
  ztp/internal/tool.go
  ztp/internal/tool_test.go
  ztp/main.go
Labels: size/XXL

#645 NO-ISSUE: Add config
  ztp/go.mod
  ztp/go.sum
  ztp/internal/cmd/edgecluster/edgecluster_cmd.go
  ztp/internal/config.go
  ztp/internal/jq.go
  ztp/internal/models/api.go
  ztp/internal/models/bmc.go
  ztp/internal/models/cluster.go
  ztp/internal/models/config.go
  ztp/internal/models/dns.go
  ztp/internal/models/ingress.go
  ztp/internal/models/nic.go
  ztp/internal/models/node.go
  ztp/internal/models/ssh.go
  ztp/main.go
Labels: size/XL

#648 NO-ISSUE: Add testss for the `jq` object
  ztp/internal/config.go
  ztp/internal/jq.go
  ztp/internal/jq_test.go
Labels: size/L

#649 NO-ISSUE: Add template object
  ztp/internal/template.go
  ztp/internal/template_test.go
Labels: size/XL

#651 NO-ISSUE: Add client based on controller-runtime
  ztp/go.mod
  ztp/go.sum
  ztp/internal/client.go
  ztp/internal/client_test.go
  ztp/internal/logging_transport_wrapper.go
Labels: size/L

#650 Adjusting the doc per https://issues.redhat.com/browse/MGMT-11220
  documentation/ztp-for-factories/ztp-create-factory-hub-cluster.adoc
Labels: documentation, size/XS

#653 Enhancing the architecture section of the doc.
  documentation/ztp-for-factories/ztp-install-factory-hubedge-architecture.adoc
Labels: documentation, size/XS

#646 Fix hub config in cases where disconnected registry was not installed
  deploy-hub-configs/04-agent-service-config.yml
  deploy-hub-configs/deploy.sh
Labels: size/M

#654 NO-ISSUE: Run tests only in Linux
  .github/workflows/check-cli.yml
Labels: size/XS

#655 NO-ISSUE: Add Kubernetes API test infrastructure
  ztp/.gitignore
  ztp/go.mod
  ztp/go.sum
  ztp/internal/client.go
  ztp/internal/client_test.go
  ztp/internal/cmd/edgecluster/edgecluster_cmd_test.go
  ztp/internal/logging_transport_wrapper.go
  ztp/internal/suite_test.go
  ztp/internal/testing/environment.go
  ztp/internal/testing/environment_ca.go
  ztp/internal/tool_test.go
Labels: size/XXL

#658 NO-ISSUE: Wait for API server ready before running tests
  ztp/internal/testing/environment.go
Labels: size/M

#659 NO-ISSUE: Add support for creating CRDs and objects in testing env
  ztp/internal/testing/environment.go
  ztp/internal/testing/environment/crds/0000_example.yaml
  ztp/internal/testing/environment/objects/0000_example.yaml
Labels: size/L

#661 NO-ISSUE: Add JQ methods to read from strings and bytes
  ztp/internal/jq.go
  ztp/internal/jq_test.go
Labels: size/M

#662 NO-ISSUE: Add methods to get/set tool env
  ztp/internal/tool.go
  ztp/main.go
Labels: size/M

#664 NO-ISSUE: Add templating package
  ztp/internal/templating/engine.go
  ztp/internal/templating/engine_test.go
  ztp/internal/templating/suite_test.go
Labels: size/L

#666 NO-ISSUE: Add object renderer
  ztp/internal/renderer.go
  ztp/internal/renderer_test.go
  ztp/internal/testing/text.go
Labels: size/XL

#657 More than one pipeline should be mentioned.
  documentation/ztp-for-factories/ztp-install-factory-pipeline-overview.adoc
  documentation/ztp-for-factories/ztp-intro-factory-install.adoc
Labels: documentation, size/XS

#668 NO-ISSUE: Add testing env CRDs
  ztp/internal/testing/environment/crds/0010_ingresscontroller.yaml
  ztp/internal/testing/environment/crds/0020_agentclusterinstall.yaml
  ztp/internal/testing/environment/crds/0030_clusterdeployment.yaml
  ztp/internal/testing/environment/crds/0040_managedcluster.yaml
  ztp/internal/testing/environment/crds/0050_infraenv.yaml
  ztp/internal/testing/environment/crds/0060_nmstateconfig.yaml
  ztp/internal/testing/environment/crds/0070_baremetalhost.yaml
  ztp/internal/testing/environment_crds.go
Labels: size/XXL

#669 NO-ISSUE: Add config loading test
  ztp/internal/config.go
  ztp/internal/config_test.go
Labels: size/L

#670 NO-ISSUE: Test loading config with multiple NICs
  ztp/internal/config_test.go
Labels: size/L

#671 NO-ISSUE: Check existence of called template
  ztp/internal/templating/engine.go
  ztp/internal/templating/engine_test.go
Labels: size/S

#672 NO-ISSUE: Support byte array as content of testing TmpFS
  ztp/internal/testing/fs.go
Labels: size/S

#673 NO-ISSUE: Explicitly load kbueconfig in client
  ztp/internal/client.go
  ztp/internal/client_test.go
Labels: size/M
