Repository rh-ecosystem-edge/ztp-pipeline-relocatable, pull requests merged in 2023-02, with the labels that each got.

#674 Prerequisite to check edge cluster is having the edgecluster.
  documentation/ztp-for-factories/ztp-post-install-edge-factory-pipeline-checks.adoc
Labels: documentation, size/XS

#680 NO-ISSUE: Add `dev cleanup` command
  ztp/internal/cmd/dev/cleanup/dev_cleanup_cmd.go
  ztp/internal/cmd/dev/dev_cmd.go
  ztp/internal/cmd/dev/setup/dev_setup_cmd.go
  ztp/internal/cmd/edgecluster/edgecluster_cmd.go
Labels: size/L

#681 NO-ISSUE: Don't create objects if they already exist
  ztp/internal/cmd/edgecluster/edgecluster_cmd.go
  ztp/internal/cmd/edgecluster_cmd_test.go
  ztp/internal/data/prd/templates/objects/090-bare-metal-host.yaml
Labels: size/L

#683 NO-ISSUE: Add `--wait` option to `edgecluster`
  ztp/internal/cmd/dev/cleanup/dev_cleanup_cmd.go
  ztp/internal/cmd/edgecluster/edgecluster_cmd.go
  ztp/internal/cmd/edgecluster_cmd_test.go
  ztp/internal/cmd/version_cmd_test.go
  ztp/internal/enricher.go
  ztp/internal/errors.go
  ztp/internal/gvks.go
  ztp/internal/logging/logger.go
  ztp/internal/tool.go
  ztp/main.go
Labels: size/XL

#685 NO-ISSUE: Add `go:generate` directives to update CRDs
  ztp/internal/data.go
Labels: size/XS

#686 NO-ISSUE: Fix command package names
  ztp/internal/cmd/dev/cleanup/dev_cleanup_cmd.go
  ztp/internal/cmd/dev/dev_cmd.go
  ztp/internal/cmd/dev/setup/dev_setup_cmd.go
  ztp/internal/cmd/version/version_cmd.go
Labels: size/XS

#676 Correcting the number of minimum required IPs.
  documentation/ztp-for-factories/ztp-create-factory-hub-cluster.adoc
Labels: documentation, size/XS

#687 NO-ISSUE: Build with Go 1.20
  .github/workflows/check-cli.yml
  ztp/go.mod
  ztp/go.sum
Labels: internal, github-actions, size/S

#688 NO-ISSUE: Add Containerfile for CLI
  .github/workflows/check-cli.yml
  ztp/.containerignore
  ztp/Containerfile
Labels: size/M

#690 NO-ISSUE: Calculate OCP versions
  ztp/internal/cmd/edgecluster/edgecluster_cmd.go
  ztp/internal/enricher.go
  ztp/internal/enricher_test.go
  ztp/internal/models/properties.go
Labels: size/XL

#691 NO-ISSUE: Replace renderer with applier
  ztp/internal/applier.go
  ztp/internal/applier_test.go
  ztp/internal/cmd/dev/cleanup/dev_cleanup_cmd.go
  ztp/internal/cmd/dev/setup/dev_setup_cmd.go
  ztp/internal/cmd/edgecluster/edgecluster_cmd.go
  ztp/internal/data/cluster/files/api_hosts
  ztp/internal/data/cluster/files/cfg-override-bmh.json
  ztp/internal/data/cluster/files/cfg-override-infraenv.json
  ztp/internal/data/cluster/files/change-def-route.service
  ztp/internal/data/cluster/files/change_def_route.sh
  ztp/internal/data/cluster/files/csr-approver.service
  ztp/internal/data/cluster/files/csr_autoapprover.sh
  ztp/internal/data/cluster/files/iface_default_hint
  ztp/internal/data/cluster/files/node-ip-config.txt
  ztp/internal/data/cluster/files/node-ip-config.yaml
  ztp/internal/data/cluster/objects/000-namespace.yaml
  ztp/internal/data/cluster/objects/010-pull-secret.yaml
  ztp/internal/data/cluster/objects/020-manifests-configmap.yaml
  ztp/internal/data/cluster/objects/030-agentclusterinstall.yaml
  ztp/internal/data/cluster/objects/040-clusterdeployment.yaml
  ztp/internal/data/cluster/objects/050-managedcluster.yaml
  ztp/internal/data/cluster/objects/060-infraenv.yaml
  ztp/internal/data/cluster/objects/070-nmstateconfig.yaml
  ztp/internal/data/cluster/objects/080-bmc-secret.yaml
  ztp/internal/data/cluster/objects/090-baremetalhost.yaml
  ztp/internal/data/cluster/objects/100-ssh-secret.yaml
  ztp/internal/gvks.go
  ztp/internal/labels/labels.go
  ztp/internal/renderer.go
Labels: size/XXL

#692 NO-ISSUE: Rename `edgecluster` to `create cluster`
  ztp/go.mod
  ztp/internal/cmd/create/cluster/create_cluster_cmd.go
  ztp/internal/cmd/create/create_cmd.go
  ztp/internal/cmd/create_cluster_cmd_test.go
  ztp/internal/cmd/version_cmd_test.go
  ztp/main.go
Labels: size/M

#693 NO-ISSUE: Move exit error to separate package
  ztp/internal/cmd/create/cluster/create_cluster_cmd.go
  ztp/internal/cmd/dev/cleanup/dev_cleanup_cmd.go
  ztp/internal/cmd/dev/setup/dev_setup_cmd.go
  ztp/internal/exit/error.go
  ztp/main.go
Labels: size/M

#695 NO-ISSUE: Add applier listener
  ztp/go.mod
  ztp/internal/applier.go
  ztp/internal/applier_listener.go
  ztp/internal/cmd/create/cluster/create_cluster_cmd.go
  ztp/internal/cmd/dev/setup/dev_setup_cmd.go
Labels: size/L

#696 MGMT-13583: Update MCE mirrored channels
  deploy-disconnected-registry/oc-mirror-config-hub.yaml
Labels: size/XS

#697 NO-ISSUE: Add --log-level and --log-file options
  ztp/internal/applier_test.go
  ztp/internal/client_test.go
  ztp/internal/cmd/create_cluster_cmd_test.go
  ztp/internal/config_test.go
  ztp/internal/context_test.go
  ztp/internal/enricher_test.go
  ztp/internal/jq_test.go
  ztp/internal/logging/flags.go
  ztp/internal/logging/logger.go
  ztp/internal/logging/logger_test.go
  ztp/internal/logging/transport_wrapper.go
  ztp/internal/logging/transport_wrapper_test.go
  ztp/internal/templating/engine_test.go
  ztp/internal/tool.go
  ztp/internal/tool_test.go
Labels: size/L

#698 NO-ISSUE: Take pull secret from hub
  ztp/internal/applier_listener.go
  ztp/internal/cmd/create_cluster_cmd_test.go
  ztp/internal/data/dev/files/pull-secret.json
  ztp/internal/data/dev/objects/0010-ingresscontroller_namespace.yaml
  ztp/internal/data/dev/objects/0020-ingresscontroller.yaml
  ztp/internal/data/dev/objects/0030-config_namespace.yaml
  ztp/internal/data/dev/objects/0040-pull-secret.yaml
  ztp/internal/enricher.go
  ztp/internal/enricher_test.go
Labels: size/M

#699 NO-ISSUE: Fix overlaping CIDRs
  ztp/internal/enricher.go
  ztp/internal/enricher_test.go
Labels: size/M

#700 NO-ISSUE: Fix assignment of internal IP addresses
  ztp/go.mod
  ztp/internal/data/cluster/objects/070-nmstateconfig.yaml
  ztp/internal/enricher.go
  ztp/internal/enricher_test.go
Labels: size/L

#701 NO-ISSUE: Fix calculation of prefix length
  ztp/internal/data/cluster/objects/070-nmstateconfig.yaml
  ztp/internal/enricher.go
  ztp/internal/enricher_test.go
  ztp/internal/models/nic.go
Labels: size/S

#702 NO-ISSUE: Fix permissions of log file
  ztp/internal/logging/logger.go
  ztp/internal/logging/logger_test.go
Labels: size/M

#703 NO-ISSUE: Add test for log flags
  ztp/internal/logging/logger_test.go
Labels: size/M

#704 NO-ISSUE: Fix calculation of DNS domain
  ztp/internal/cmd/create_cluster_cmd_test.go
  ztp/internal/data/dev/files/pull-secret.json
  ztp/internal/data/dev/objects/0020-ingresscontroller.yaml
  ztp/internal/enricher.go
  ztp/internal/enricher_test.go
Labels: size/M

#705 NO-ISSUE: Fix generated ignition
  ztp/go.mod
  ztp/go.sum
  ztp/internal/cmd/create_cluster_cmd_test.go
  ztp/internal/data/cluster/files/cfg-override-bmh.json
  ztp/internal/data/cluster/files/change-def-route.service
  ztp/internal/data/cluster/objects/060-infraenv.yaml
Labels: size/M

#708 NO-ISSUE: Don't generate SSH keys if they already exist
  ztp/internal/enricher.go
  ztp/internal/enricher_test.go
Labels: size/L

#711 NO-ISSUE: Wait for CRD before creating object
  ztp/internal/applier.go
  ztp/internal/applier_listener.go
  ztp/internal/applier_test.go
Labels: size/L

#712 NO-ISSUE: Improve applier listener
  ztp/go.mod
  ztp/go.sum
  ztp/internal/applier.go
  ztp/internal/applier_listener.go
  ztp/internal/applier_listener_test.go
Labels: size/L

#713 NO-ISSUE: Redirect klog to tool log
  ztp/go.mod
  ztp/internal/tool.go
  ztp/internal/tool_test.go
Labels: size/M

#714 NO-ISSUE: Fetch external IP addresses from agents
  ztp/internal/data.go
  ztp/internal/data/dev/crds/0015_agent.yaml
  ztp/internal/enricher.go
  ztp/internal/enricher_test.go
  ztp/internal/gvks.go
  ztp/internal/jq_test.go
Labels: size/XL

#715 NO-ISSUE: Get kubeconfig from secret
  ztp/internal/applier_test.go
  ztp/internal/client.go
  ztp/internal/enricher.go
  ztp/internal/enricher_test.go
  ztp/internal/models/cluster.go
Labels: size/L

#716 Set task timeout
  pipelines/resources/deploy-ztp-edgeclusters.yaml
Labels: pipelines, size/XS

#718 NO-ISSUE: Calculate image set
  ztp/internal/cmd/create/cluster/create_cluster_cmd.go
  ztp/internal/cmd/create_cluster_cmd_test.go
  ztp/internal/cmd/delete/cluster/delete_cluster_cmd.go
  ztp/internal/config.go
  ztp/internal/enricher.go
  ztp/internal/enricher_test.go
  ztp/internal/models/cluster.go
  ztp/internal/models/config.go
  ztp/internal/models/properties.go
Labels: size/L

#720 NO-ISSUE: Don't try to get `cluster-info`
  ztp/internal/client.go
Labels: size/S

#717 Mirror OCP release candidates
  deploy-disconnected-registry/oc-mirror-config-edgecluster.yaml
  deploy-disconnected-registry/oc-mirror-config-hub.yaml
Labels: registry, size/XS

#722 NO-ISSUE: Fix use of `-w` without `name` in docs
  documentation/ztp-for-factories/ztp-install-factory-edge-pipeline.adoc
  documentation/ztp-for-factories/ztp-install-factory-pipeline.adoc
Labels: documentation, size/S

#723 NO-ISSUE: Load Kubeconfig fron default locations
  ztp/internal/client.go
  ztp/internal/cmd/create/cluster/create_cluster_cmd.go
  ztp/internal/cmd/delete/cluster/delete_cluster_cmd.go
  ztp/internal/cmd/dev/cleanup/dev_cleanup_cmd.go
  ztp/internal/cmd/dev/setup/dev_setup_cmd.go
  ztp/internal/enricher.go
  ztp/internal/tool.go
  ztp/main.go
Labels: size/L

#724 NO-ISSUE: Downgrade to Go 1.19
  .github/workflows/check-cli.yml
  ztp/Containerfile
  ztp/go.mod
Labels: size/M

#719 NO-ISSUE: Add `ztp` binary to pipeline image
  images/Containerfile.pipeline
Labels: pipelines, images, size/S

#725 Update task timeout for hub deployment
  pipelines/resources/deploy-ztp-edgeclusters-sno.yaml
  pipelines/resources/deploy-ztp-hub.yaml
Labels: pipelines, size/XS

#635 Adjusting storage requirements.
  documentation/ztp-for-factories/ztp-for-factory-prerequisites.adoc
Labels: documentation, size/XS

#726 NO-ISSUE: Fix cluster installed condition
  ztp/internal/cmd/create/cluster/create_cluster_cmd.go
Labels: size/XS

#727 NO-ISSUE: Report changes of state
  ztp/internal/cmd/create/cluster/create_cluster_cmd.go
  ztp/internal/cmd/create_cluster_cmd_test.go
  ztp/internal/testing/text.go
Labels: size/L

#729 NO-ISSUE: Add `--output` flag
  ztp/internal/cmd/create/cluster/create_cluster_cmd.go
Labels: size/M

#730 NO-ISSUE: Fix naming of nodes
  ztp/internal/cmd/create_cluster_cmd_test.go
  ztp/internal/data/cluster/objects/070-nmstateconfig.yaml
  ztp/internal/data/cluster/objects/080-bmc-secret.yaml
  ztp/internal/data/cluster/objects/090-baremetalhost.yaml
  ztp/internal/models/cluster.go
  ztp/internal/models/cluster_test.go
  ztp/internal/models/node.go
  ztp/internal/models/node_test.go
  ztp/internal/models/suite_test.go
Labels: size/L

#732 NO-ISSUE: Remove old CLI image
  .github/workflows/check-cli.yml
  ztp/.containerignore
  ztp/Containerfile
Labels: size/M

#733 NO-ISSUE: Add utilities to create/delete objects
  ztp/internal/cmd/dev/create/dev_create_cmd.go
  ztp/internal/cmd/dev/delete/dev_delete_cmd.go
  ztp/internal/cmd/dev/dev_cmd.go
Labels: size/L

#734 NO-ISSUE: Add agent and ICSP CRDs to dev env
  ztp/internal/data.go
  ztp/internal/data/dev/crds/0011_icsp.yaml
  ztp/internal/data/dev/crds/0080_olm.yaml
Labels: size/XXL

#735 NO-ISSUE: Fix parsing IPs of agents
  ztp/internal/enricher.go
  ztp/internal/enricher_test.go
Labels: size/XS

#736 NO-ISSUE: Avoid log package interferences with tests
  ztp/internal/cmd/suite_test.go
  ztp/internal/logging/suite_test.go
  ztp/internal/models/suite_test.go
  ztp/internal/suite_test.go
  ztp/internal/templating/suite_test.go
Labels: size/S

#737 NO-ISSUE: Add SSH tunnel support
  ztp/internal/applier_test.go
  ztp/internal/client.go
  ztp/internal/cmd/create/cluster/create_cluster_cmd.go
  ztp/internal/cmd/create_cluster_cmd_test.go
  ztp/internal/cmd/delete/cluster/delete_cluster_cmd.go
  ztp/internal/cmd/dev/cleanup/dev_cleanup_cmd.go
  ztp/internal/cmd/dev/create/dev_create_cmd.go
  ztp/internal/cmd/dev/delete/dev_delete_cmd.go
  ztp/internal/cmd/dev/setup/dev_setup_cmd.go
  ztp/internal/enricher_test.go
  ztp/internal/logging/list.go
  ztp/internal/logging/list_test.go
Labels: size/L

#738 NO-ISSUE: Add console
  ztp/internal/applier_listener.go
  ztp/internal/applier_listener_test.go
  ztp/internal/cmd/create/cluster/create_cluster_cmd.go
  ztp/internal/cmd/delete/cluster/delete_cluster_cmd.go
  ztp/internal/cmd/dev/cleanup/dev_cleanup_cmd.go
  ztp/internal/cmd/dev/create/dev_create_cmd.go
  ztp/internal/cmd/dev/delete/dev_delete_cmd.go
  ztp/internal/cmd/dev/setup/dev_setup_cmd.go
  ztp/internal/cmd/version/version_cmd.go
  ztp/internal/console.go
  ztp/internal/console_test.go
  ztp/internal/context.go
  ztp/internal/context_test.go
  ztp/internal/tool.go
Labels: size/XL

#741 NO-ISSUE: Rename `applier.Create` to `applier.Apply`
  ztp/internal/applier.go
  ztp/internal/applier_test.go
  ztp/internal/cmd/create/cluster/create_cluster_cmd.go
  ztp/internal/cmd/dev/apply/dev_apply_cmd.go
  ztp/internal/cmd/dev/delete/dev_delete_cmd.go
  ztp/internal/cmd/dev/dev_cmd.go
  ztp/internal/cmd/dev/setup/dev_setup_cmd.go
  ztp/internal/enricher_test.go
Labels: size/M

#742 NO-ISSUE: Move config code to a separate package
  ztp/internal/applier.go
  ztp/internal/cmd/create/cluster/create_cluster_cmd.go
  ztp/internal/cmd/delete/cluster/delete_cluster_cmd.go
  ztp/internal/config/loader.go
  ztp/internal/config/loader_test.go
  ztp/internal/config/suite_test.go
  ztp/internal/enricher.go
  ztp/internal/jq/suite_test.go
  ztp/internal/jq/tool.go
  ztp/internal/jq/tool_test.go
Labels: size/L

#743 NO-ISSUE: Add shared code to setup config flags
  ztp/internal/applier.go
  ztp/internal/cmd/create/cluster/create_cluster_cmd.go
  ztp/internal/cmd/delete/cluster/delete_cluster_cmd.go
  ztp/internal/config/flags.go
  ztp/internal/config/loader.go
  ztp/internal/config/loader_test.go
  ztp/internal/enricher.go
  ztp/internal/jq/tool.go
Labels: size/L

#652 MGMT-13430: Switch to using a secondary IP rather than vlans
  .dockerignore
  Makefile
  deploy-edgecluster/30-nodenet-crio.conf
  deploy-edgecluster/30-nodenet.conf
  deploy-edgecluster/99-add-host-int-ip.sh
  deploy-edgecluster/bmh-ignition.json
  deploy-edgecluster/change_def_route.sh
  deploy-edgecluster/configure_disconnected.sh
  deploy-edgecluster/render_edgeclusters.sh
  deploy-metallb/deploy.sh
  deploy-worker/30-nodenet-crio.conf
  deploy-worker/30-nodenet.conf
  deploy-worker/99-add-host-int-ip.sh
  deploy-worker/bmh-ignition.json
  deploy-worker/render_worker.sh
  shared-utils/common.sh
Labels: internal, metallb, worker, size/L, edgecluster

#746 NO-ISSUE: Improve waiting for deleted
  ztp/internal/applier.go
  ztp/internal/applier_listener.go
  ztp/internal/applier_test.go
Labels: size/M

#749 Remove change-def-route
  deploy-edgecluster/bmh-ignition.json
  deploy-edgecluster/change_def_route.sh
  deploy-edgecluster/render_edgeclusters.sh
Labels: size/M, edgecluster

#751 NO-ISSUE: Adjust CLI to use additional IPs instead of VLAN
  ztp/internal/config/loader.go
  ztp/internal/data/cluster/files/add-internal-ip-bmh.sh
  ztp/internal/data/cluster/files/add-internal-ip-infraenv.sh
  ztp/internal/data/cluster/files/cfg-override-bmh.json
  ztp/internal/data/cluster/files/cfg-override-infraenv.json
  ztp/internal/data/cluster/files/change-def-route.service
  ztp/internal/data/cluster/files/change_def_route.sh
  ztp/internal/data/cluster/files/iface_default_hint
  ztp/internal/data/cluster/files/nodenet-crio.conf
  ztp/internal/data/cluster/files/nodenet-kubelet.conf
  ztp/internal/data/cluster/objects/070-nmstateconfig.yaml
  ztp/internal/data/cluster/objects/090-baremetalhost.yaml
  ztp/internal/enricher.go
  ztp/internal/enricher_test.go
  ztp/internal/models/ip.go
  ztp/internal/models/ip_test.go
  ztp/internal/models/nic.go
  ztp/internal/models/node.go
Labels: size/L

#750 Select agents only for masters
  shared-utils/common.sh
Labels: internal, size/XS

#752 NO-ISSUE: Don't explicitly delete cluster deployments
  ztp/internal/applier.go
  ztp/internal/cmd/delete/cluster/delete_cluster_cmd.go
Labels: size/M

#753 Don't set the internal IP twice
  deploy-edgecluster/render_edgeclusters.sh
Labels: size/XS, edgecluster

#755 NO-ISSUE: Stop waiting when cluster installation fails
  ztp/internal/cmd/create/cluster/create_cluster_cmd.go
  ztp/internal/cmd/create_cluster_cmd_test.go
Labels: size/L

#756 Don't set secondary IP on br-ex if there are 2 interfaces
  deploy-edgecluster/99-add-host-int-ip.sh
Labels: size/S, edgecluster

#754 Setting timeout for metallb.
  pipelines/resources/deploy-ztp-edgeclusters-connected.yaml
  pipelines/resources/deploy-ztp-edgeclusters-sno-connected.yaml
  pipelines/resources/deploy-ztp-edgeclusters-sno.yaml
  pipelines/resources/deploy-ztp-edgeclusters.yaml
Labels: pipelines, size/XS

#694 Providing clarity to network requirement related sentence.
  documentation/ztp-for-factories/ztp-create-factory-hub-cluster.adoc
Labels: documentation, size/XS

#758 NO-ISSUE: Fix wait for CRD
  ztp/internal/applier.go
  ztp/internal/applier_test.go
Labels: size/L

#760 NO-ISSUE: Improve wait for CRD
  ztp/go.mod
  ztp/go.sum
  ztp/internal/applier.go
  ztp/internal/applier_test.go
Labels: size/L

#759 NO-ISSUE: Fix assignment of API and ingress addresses
  ztp/internal/data/cluster/files/api_hosts
  ztp/internal/data/cluster/objects/030-agentclusterinstall.yaml
  ztp/internal/data/metallb/objects/0100-metallb-api-ipaddresspool.yaml
  ztp/internal/data/metallb/objects/0120-metallb-ingress-ipaddresspool.yaml
  ztp/internal/enricher.go
  ztp/internal/enricher_test.go
  ztp/internal/models/api.go
  ztp/internal/models/ingress.go
Labels: size/L

#761 NO-ISSUE: Route via hosts
  ztp/internal/data/cluster/files/cluster-network-03-config.yml
  ztp/internal/data/cluster/objects/020-manifests-configmap.yaml
Labels: size/S

#762 NO-ISSUE: Add support for custom log fields
  ztp/internal/logging/flags.go
  ztp/internal/logging/logger.go
  ztp/internal/logging/logger_test.go
  ztp/internal/logging/transport_wrapper.go
Labels: size/L

#763 NO-ISSUE: Add options to enable/disable HTTP logging
  ztp/internal/client.go
  ztp/internal/client_test.go
  ztp/internal/cmd/create/cluster/create_cluster_cmd.go
  ztp/internal/cmd/create/metallb/create_metallb_cmd.go
  ztp/internal/cmd/delete/cluster/delete_cluster_cmd.go
  ztp/internal/cmd/dev/apply/dev_apply_cmd.go
  ztp/internal/cmd/dev/cleanup/dev_cleanup_cmd.go
  ztp/internal/cmd/dev/delete/dev_delete_cmd.go
  ztp/internal/cmd/dev/setup/dev_setup_cmd.go
  ztp/internal/logging/flags.go
  ztp/internal/logging/logger.go
  ztp/internal/logging/transport_wrapper.go
  ztp/internal/logging/transport_wrapper_test.go
Labels: size/XL

#765 NO-ISSUE: Fix name of API L2 advertisement template
  ztp/internal/data/metallb/objects/0140-metallb-api-l2advertisement.yaml
Labels: size/XS

#766 NO-ISSUE: Fix selectors of node network configuration policies
  ztp/internal/data/metallb/objects/0150-nncp.yaml
Labels: size/XS

#767 NO-ISSUE: Retry when creation fails with 500
  ztp/internal/applier.go
Labels: size/S

#768 NO-ISSUE: Use %w instead of %v
  ztp/internal/applier.go
  ztp/internal/config/loader.go
  ztp/internal/enricher.go
  ztp/internal/jq/tool.go
Labels: size/M

#769 NO-ISSUE: Add `--color` flag
  ztp/internal/console.go
  ztp/internal/console_flags.go
  ztp/internal/tool.go
Labels: size/M

#770 NO-ISSUE: Replace console args
  ztp/internal/console.go
  ztp/internal/console_test.go
Labels: size/L

#771 NO-ISSUE: Add `create icsp` command
  ztp/internal/cmd/create/create_cmd.go
  ztp/internal/cmd/create/icsp/create_icsp_cmd.go
  ztp/internal/data/dev/objects/0050-marketplace-namespace.yaml
  ztp/internal/data/dev/objects/0060-catalog-sources.yaml
  ztp/internal/data/dev/objects/0070-registry-namespace.yaml
  ztp/internal/data/dev/objects/0080-registry-configmap.yaml
  ztp/internal/gvks.go
Labels: size/L

#773 NO-ISSUE: Add missing error check in enricher
  ztp/internal/enricher.go
Labels: size/XS

#772 Align with latest kcli
  hack/deploy-hub-local/build-hub.sh
Labels: internal, size/XS

#774 NO-ISSUE: Trust registry
  ztp/internal/cmd/create/icsp/create_icsp_cmd.go
  ztp/internal/data.go
  ztp/internal/data/dev/crds/0012_image.yaml
  ztp/internal/data/dev/objects/0080-registry-configmap.yaml
  ztp/internal/data/dev/objects/image-config.yaml
  ztp/internal/enricher.go
  ztp/internal/enricher_test.go
  ztp/internal/gvks.go
Labels: size/L

#775 NO-ISSUE: Use calculated hostname for BMH and BMC secrets
  ztp/internal/data/cluster/objects/070-nmstateconfig.yaml
  ztp/internal/data/cluster/objects/080-bmc-secret.yaml
  ztp/internal/data/cluster/objects/090-baremetalhost.yaml
Labels: size/XS

#757 NO-ISSUE: Add internal IP to `br-ex`
  ztp/internal/data/cluster/files/add-internal-ip-bmh.sh
Labels: size/XS

#777 NO-ISSUE: Add `data` template function
  ztp/internal/data/cluster/objects/090-baremetalhost.yaml
  ztp/internal/templating/engine.go
  ztp/internal/templating/engine_test.go
  ztp/internal/testing/text.go
Labels: size/L

#780 Remove a stale symlink.
  deploy-worker/change_def_route.sh
Labels: size/XS

#781 NO-ISSUE: Add `--mute` flag to console
  ztp/internal/console.go
  ztp/internal/console_flags.go
  ztp/internal/console_test.go
Labels: size/L

#748 Switch ZTPFW to 4.12
  Makefile
  deploy-disconnected-registry/oc-mirror-config-edgecluster.yaml
  deploy-disconnected-registry/oc-mirror-config-hub.yaml
  deploy-edgecluster/render_edgeclusters.sh
  deploy-lvmo/deploy-hub.sh
  deploy-lvmo/deploy.sh
  deploy-lvmo/manifests/03-LVMO-Subscription.yaml
  deploy-lvmo/manifests/05-Hub-PVC.yaml
  deploy-lvmo/verify.sh
  deploy-lvmo/verify_hub.sh
  deploy-odf/manifests/04-MCG-StorageCluster.yaml
  hack/deploy-hub-local/build-hub.sh
  hack/deploy-hub-local/create-vm-sno.yml
  hack/deploy-hub-local/create-vm.yml
Labels: internal, registry, odf, size/M, edgecluster

#776 Removing the -K argument
  documentation/ztp-for-factories/ztp-install-openshift-pipelines.adoc
Labels: documentation, size/XS

#783 NO-ISSUE: Remove `node-ip-config.yml` overriden manifest
  ztp/internal/data/cluster/files/node-ip-config.txt
  ztp/internal/data/cluster/files/node-ip-config.yaml
  ztp/internal/data/cluster/objects/020-manifests-configmap.yaml
Labels: size/S

#731 MGMT-13114: Replace `deploy-edgecluster` scripts with `ztp`
  pipelines/resources/deploy-ztp-edgeclusters-connected.yaml
  pipelines/resources/deploy-ztp-edgeclusters-sno-connected.yaml
  pipelines/resources/deploy-ztp-edgeclusters-sno.yaml
  pipelines/resources/deploy-ztp-edgeclusters.yaml
  pipelines/resources/edgeclusters/edgecluster-deploy-edgecluster.yaml
Labels: pipelines, size/M

#787 NO-ISSUE: Check pipelines
  .github/workflows/check-pipelines.yml
Labels: size/M

#788 NO-ISSUE: Don't check CLI if it didnt' change
  .github/workflows/check-cli.yml
Labels: size/XS

#786 NO-ISSUE: Remove duplicated `ztp-log-level` parameter
  pipelines/resources/deploy-ztp-edgeclusters.yaml
Labels: size/XS

#162 Deploy 4-nodes clusters in one step
  pipelines/resources/deploy-ztp-edgeclusters-connected.yaml
  pipelines/resources/deploy-ztp-edgeclusters.yaml
  ztp/internal/data/cluster/objects/030-agentclusterinstall.yaml
  ztp/internal/data/cluster/objects/070-nmstateconfig.yaml
  ztp/internal/data/cluster/objects/080-bmc-secret.yaml
  ztp/internal/data/cluster/objects/090-baremetalhost.yaml
Labels: pipelines, spoke, worker, size/M

#785 Aligning the documentation with the same args.
  documentation/ztp-for-factories/ztp-for-factory-development.adoc
  documentation/ztp-for-factories/ztp-for-factory-installation-workflow.adoc
Labels: documentation, size/XS

#790 NO-ISSUE: Adjust some log levels
  ztp/internal/enricher.go
Labels: size/M
