Repository rh-ecosystem-edge/ztp-pipeline-relocatable, pull requests merged in 2023-03, with the labels that each got.

#791 Enhance the requirements for the edge cluster.
  documentation/ztp-for-factories/ztp-install-factory-edge-pipeline.adoc
Labels: documentation, size/XS

#792 NO-ISSUE: Redact security sensitive log fields
  ztp/internal/enricher.go
  ztp/internal/logging/flags.go
  ztp/internal/logging/logger.go
  ztp/internal/logging/logger_test.go
  ztp/internal/logging/sink.go
Labels: size/L

#793 NO-ISSUE: Move `Dedent` to new `text` package
  ztp/internal/applier_test.go
  ztp/internal/cmd/create_cluster_cmd_test.go
  ztp/internal/config/loader_test.go
  ztp/internal/enricher_test.go
  ztp/internal/logging/flags.go
  ztp/internal/templating/engine_test.go
  ztp/internal/testing/template.go
  ztp/internal/text/dedent.go
  ztp/internal/text/dedent_test.go
  ztp/internal/text/suite_test.go
Labels: size/L

#795 NO-ISSUE: Fix wait for CRD
  ztp/internal/applier.go
  ztp/internal/applier_test.go
Labels: size/M

#797 Add role annotation for workers
  ztp/internal/data/cluster/objects/090-baremetalhost.yaml
Labels: size/XS

#799 NO-ISSUE: Add order prefix to UI objects
  ztp/internal/data/ui/objects/0010-namespace.yaml
  ztp/internal/data/ui/objects/0020-clusterrolebinding.yaml
  ztp/internal/data/ui/objects/0030-deployment.yaml
  ztp/internal/data/ui/objects/0040-oauthclient.yaml
  ztp/internal/data/ui/objects/0050-service.yaml
  ztp/internal/data/ui/objects/0060-route.yaml
Labels: size/XS

#798 NO-ISSUE: Add `create lso` command
  ztp/internal/applier.go
  ztp/internal/cmd/create/cluster/create_cluster_cmd.go
  ztp/internal/cmd/create/create_cmd.go
  ztp/internal/cmd/create/lso/create_lso_cmd.go
  ztp/internal/data.go
  ztp/internal/data/dev/crds/0160_localvolume.yaml
  ztp/internal/data/lso/objects/0010-namespace.yaml
  ztp/internal/data/lso/objects/0020-operatorgroup.yaml
  ztp/internal/data/lso/objects/0030-subscription.yaml
  ztp/internal/data/lso/objects/0040-localvolume.yaml
  ztp/internal/data/lso/scripts/wipe.sh
  ztp/internal/gvks.go
Labels: size/XL

#802 NO-ISSUE: Delete CRDs when deleting metal load balancer
  ztp/internal/client.go
  ztp/internal/cmd/create/metallb/create_metallb_cmd.go
  ztp/internal/cmd/delete/metallb/delete_metallb_cmd.go
Labels: size/L

#806 NO-ISSUE: Add `delete lso` command
  ztp/internal/cmd/delete/delete_cmd.go
  ztp/internal/cmd/delete/lso/delete_lso_cmd.go
  ztp/internal/data/lso/objects/0020-operatorgroup.yaml
  ztp/internal/data/lso/objects/0030-subscription.yaml
  ztp/internal/data/lso/objects/0040-localvolume.yaml
Labels: size/L

#808 MGMT-13854: Fail installation if it moves to `error`
  ztp/internal/cmd/create/cluster/create_cluster_cmd.go
  ztp/internal/cmd/create_cluster_cmd_test.go
Labels: size/L

#809 NO-ISSUE: Simplify create cluster command tests
  ztp/go.mod
  ztp/go.sum
  ztp/internal/client.go
  ztp/internal/cmd/create_cluster_cmd_test.go
  ztp/internal/testing/manager.go
Labels: size/XXL

#807 NO-ISSUE: Simplify `delete ui` command
  ztp/internal/cmd/delete/ui/delete_ui_cmd.go
Labels: size/S

#811 NO-ISSUE: Supress noise HTTP logs
  ztp/internal/client.go
  ztp/internal/client_test.go
  ztp/internal/logging/transport_wrapper.go
  ztp/internal/logging/transport_wrapper_test.go
Labels: size/L

#812 NO-ISSUE: Don't repeat status change messages
  ztp/internal/cmd/create/cluster/create_cluster_cmd.go
Labels: size/S

#813 NO-ISSUE: Wait for API reachability in `create metallb`
  ztp/internal/cmd/create/metallb/create_metallb_cmd.go
Labels: size/L

#816 NO-ISSUE: Add `dev shell` command
  ztp/internal/cmd/dev/dev_cleanup_cmd.go
  ztp/internal/cmd/dev/dev_setup_cmd.go
  ztp/internal/cmd/dev/dev_shell_cmd.go
  ztp/internal/cmd/dev/dev_ssh_cmd.go
  ztp/internal/cmd/dev/dev_templates.go
  ztp/internal/cmd/dev/templates/setup/crds/0010_ingresscontroller.yaml
  ztp/internal/cmd/dev/templates/setup/crds/0011_icsp.yaml
  ztp/internal/cmd/dev/templates/setup/crds/0012_image.yaml
  ztp/internal/cmd/dev/templates/setup/crds/0015_agent.yaml
  ztp/internal/cmd/dev/templates/setup/crds/0020_agentclusterinstall.yaml
  ztp/internal/cmd/dev/templates/setup/crds/0030_clusterdeployment.yaml
  ztp/internal/cmd/dev/templates/setup/crds/0040_managedcluster.yaml
  ztp/internal/cmd/dev/templates/setup/crds/0050_infraenv.yaml
  ztp/internal/cmd/dev/templates/setup/crds/0060_nmstateconfig.yaml
  ztp/internal/cmd/dev/templates/setup/crds/0070_baremetalhost.yaml
  ztp/internal/cmd/dev/templates/setup/crds/0080_olm.yaml
  ztp/internal/cmd/dev/templates/setup/crds/0090_metallb.yaml
  ztp/internal/cmd/dev/templates/setup/crds/0100_ipaddresspool.yaml
  ztp/internal/cmd/dev/templates/setup/crds/0110_l2adverisements.yaml
  ztp/internal/cmd/dev/templates/setup/crds/0120_nmstate.yaml
  ztp/internal/cmd/dev/templates/setup/crds/0130_ncnp.yaml
  ztp/internal/cmd/dev/templates/setup/crds/0140_oauthclient.yaml
  ztp/internal/cmd/dev/templates/setup/crds/0150_route.yaml
  ztp/internal/cmd/dev/templates/setup/crds/0160_localvolume.yaml
  ztp/internal/cmd/dev/templates/setup/files/pull-secret.json
  ztp/internal/cmd/dev/templates/setup/objects/0050-marketplace-namespace.yaml
  ztp/internal/cmd/dev/templates/setup/objects/0060-catalog-sources.yaml
  ztp/internal/cmd/dev/templates/setup/objects/0070-registry-namespace.yaml
  ztp/internal/cmd/dev/templates/setup/objects/0080-registry-configmap.yaml
  ztp/internal/cmd/dev/templates/setup/objects/config-namespace.yaml
  ztp/internal/cmd/dev/templates/setup/objects/image-config.yaml
  ztp/internal/cmd/dev/templates/setup/objects/ingress-namespace.yaml
  ztp/internal/cmd/dev/templates/setup/objects/ingress-operator-namespace.yaml
  ztp/internal/cmd/dev/templates/setup/objects/ingresscontroller.yaml
  ztp/internal/cmd/dev/templates/setup/objects/kube-apiserver-namespace.yaml
  ztp/internal/cmd/dev/templates/setup/objects/pull-secret.yaml
  ztp/internal/cmd/dev/templates/shell/bashrc
  ztp/internal/cmd/dev/templates/shell/ssh_config
  ztp/internal/cmd/dev_cmd.go
Labels: size/L

#817 NO-ISSUE: Fix `create lso` command
  ztp/internal/cmd/lso/create_lso_cmd.go
  ztp/internal/cmd/lso/delete_lso_cmd.go
Labels: size/S

#819 NO-ISSUE: Fix API client log filter
  ztp/internal/client.go
  ztp/internal/client_test.go
Labels: size/S

#818 NO-ISSUE: Add `create odf` command
  ztp/internal/cmd/create_cmd.go
  ztp/internal/cmd/dev/dev_templates.go
  ztp/internal/cmd/dev/templates/setup/crds/0170_backingstore.yaml
  ztp/internal/cmd/odf/create_odf_cmd.go
  ztp/internal/cmd/odf/odf_templates.go
  ztp/internal/cmd/odf/templates/objects/0010-namespace.yaml
  ztp/internal/cmd/odf/templates/objects/0020-operatorgroup.yaml
  ztp/internal/cmd/odf/templates/objects/0030-subscription.yaml
  ztp/internal/cmd/odf/templates/objects/0040-storagecluster.yaml
  ztp/internal/gvks.go
  ztp/internal/models/properties.go
Labels: size/XXL

#820 MGMT-13924: Restart watches when API server is restarted
  ztp/internal/client.go
  ztp/internal/logging/sink.go
Labels: size/L

#821 NO-ISSUE: Ignore bookmark events
  ztp/internal/applier.go
  ztp/internal/cmd/cluster/create_cluster_cmd.go
Labels: size/S

#823 NO-ISSUE: Fix waiting for metal load balancer
  ztp/internal/cmd/metallb/create_metallb_cmd.go
Labels: size/S

#784 MGMT-13116: Use the CLI in the `metallb` step
  pipelines/resources/deploy-ztp-edgeclusters-connected.yaml
  pipelines/resources/deploy-ztp-edgeclusters-sno-connected.yaml
  pipelines/resources/deploy-ztp-edgeclusters-sno.yaml
  pipelines/resources/deploy-ztp-edgeclusters.yaml
  pipelines/resources/edgeclusters/edgecluster-deploy-edgecluster.yaml
  pipelines/resources/edgeclusters/edgecluster-deploy-icsp-edgeclusters-pre.yaml
  pipelines/resources/edgeclusters/edgecluster-deploy-metallb.yaml
Labels: pipelines, size/L

#826 MGMT-13974: Remove `--wipe` option of `create lso`
  ztp/internal/annotations/annotations.go
  ztp/internal/cmd/lso/create_lso_cmd.go
  ztp/internal/cmd/lso/delete_lso_cmd.go
Labels: size/L

#825 NO-ISSUE: Use CLI in `deploy-lso` and `deploy-odf` steps
  pipelines/resources/deploy-ztp-edgeclusters-connected.yaml
  pipelines/resources/deploy-ztp-edgeclusters-sno-connected.yaml
  pipelines/resources/deploy-ztp-edgeclusters-sno.yaml
  pipelines/resources/deploy-ztp-edgeclusters.yaml
  pipelines/resources/edgeclusters/edgecluster-deploy-lso.yaml
  pipelines/resources/edgeclusters/edgecluster-deploy-odf.yaml
Labels: pipelines, size/M

#828 NO-ISSUE: Use CLI in `deploy-ui` step
  pipelines/resources/deploy-ztp-edgeclusters-connected.yaml
  pipelines/resources/deploy-ztp-edgeclusters-sno-connected.yaml
  pipelines/resources/deploy-ztp-edgeclusters-sno.yaml
  pipelines/resources/deploy-ztp-edgeclusters.yaml
  pipelines/resources/edgeclusters/edgecluster-deploy-ui.yaml
Labels: pipelines, size/M

#829 NO-ISSUE: Simplify labeling and annotating
  ztp/internal/client.go
  ztp/internal/client_test.go
  ztp/internal/cmd/lso/create_lso_cmd.go
  ztp/internal/cmd/lso/delete_lso_cmd.go
  ztp/internal/cmd/odf/create_odf_cmd.go
Labels: size/XL

#831 NO-ISSUE: Add registry tool
  ztp/internal/cmd/icsp/create_icsp_cmd.go
  ztp/internal/registry_tool.go
  ztp/internal/registry_tool_test.go
Labels: size/XL

#832 NO-ISSUE: Remove warn of custom names in registry tool
  ztp/internal/registry_tool.go
Labels: size/S

#833 NO-ISSUE: Improve registry tool
  ztp/internal/cmd/icsp/create_icsp_cmd.go
  ztp/internal/registry_tool.go
  ztp/internal/registry_tool_test.go
Labels: size/L

#834 NO-ISSUE: Add `create registry` command
  ztp/internal/client.go
  ztp/internal/cmd/create_cmd.go
  ztp/internal/cmd/delete_cmd.go
  ztp/internal/cmd/dev/dev_shell_cmd.go
  ztp/internal/cmd/registry/create_registry_cmd.go
  ztp/internal/cmd/registry/delete_registry_cmd.go
  ztp/internal/cmd/registry/registry_templates.go
  ztp/internal/cmd/registry/templates/quay/files/config.yaml
  ztp/internal/cmd/registry/templates/quay/objects/0010-namespace.yaml
  ztp/internal/cmd/registry/templates/quay/objects/0020-operatorgroup.yaml
  ztp/internal/cmd/registry/templates/quay/objects/0030-subscription.yaml
  ztp/internal/cmd/registry/templates/quay/objects/0040-config.yaml
  ztp/internal/cmd/registry/templates/quay/objects/0050-registry.yaml
  ztp/internal/cmd/registry/templates/scripts/install_registry_ca.sh
  ztp/internal/gvks.go
  ztp/internal/quay/client.go
  ztp/internal/quay/client_test.go
  ztp/internal/quay/error.go
  ztp/internal/quay/organization.go
  ztp/internal/quay/suite_test.go
  ztp/internal/quay/user.go
Labels: size/XXL

#835 NO-ISSUE: Fix generation of registry auth
  ztp/internal/cmd/registry/create_registry_cmd.go
Labels: size/L
